- hosts: webservers
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: Install Node.js 16 and Git on RedHat machine
      yum:
        name:
          - npm
          - git
        state: present
      when: ansible_distribution=="RedHat"

    - name: Install Node.js 16 and Git on Ubuntu machine
      apt:
        name:
          - npm
          - git
        state: present
      when: ansible_distribution=="Ubuntu"

    - name: Clone Git repository
      git:
        repo: https://github.com/harshm1225/reactjsdemo-ansible.git
        dest: /app
        force: yes

    - name: Install project dependencies with npm
      command: /usr/bin/npm install
      args:
        chdir: /app

    - name: Run npm build in Ubuntu machine
      command: /usr/bin/npm run build
      args:
        chdir: /app
      when: ansible_distribution=="Ubuntu"

    - name: Run npm build in RedHat machine
      command: /usr/bin/npm run build
      args:
        chdir: /app
      when: ansible_distribution=="RedHat"

    - name: Install Apache Web Server on Ubuntu machine
      apt:
        name: apache2
        state: latest
        update_cache: yes
      when: ansible_distribution=="Ubuntu"

    - name: Install Apache Web Server on RedHat machine
      yum:
        name: httpd
        state: latest
        update_cache: yes
      when: ansible_distribution=="RedHat"

    - name: Enable Apache Web Server Service on Ubuntu machine
      service:
        name: apache2
        enabled: true
        state: started
      when: ansible_distribution=="Ubuntu"

    - name: Enable Apache Web Server Service on RedHat machine
      service:
        name: httpd
        enabled: true
        state: started
      when: ansible_distribution=="RedHat"

   
    - name: Copy index.html to Default Apache Document root
      copy:
       src: /app/build
       dest: /var/www/html
       remote_src: yes
      

