---
# Playbook to set up a web server environment with Node.js, Git, and Apache on RedHat and Ubuntu machines

- hosts: webservers
  become: yes
  become_method: sudo
  become_user: root

  tasks:

    # Install Node.js and Git on RedHat machine
    - name: Install Node.js and Git on RedHat machine
      dnf:
        name:
          - nodejs
          - npm
          - git
        state: present
        update_cache: yes
      when: ansible_distribution=="RedHat"

    # Install Node.js 16 and Git on Ubuntu machine
    - name: Install Node.js 16 and Git on Ubuntu machine
      apt:
        name:
          - nodejs
          - git
          - npm
        state: present
        update_cache: yes
      when: ansible_distribution=="Ubuntu"

    # Clone Git repository
    - name: Clone Git repository
      git:
        repo: https://github.com/amolshete/reactjs-demo.git
        dest: /app
        force: yes

    # Install project dependencies with npm
    - name: Install project dependencies with npm
      command: /usr/bin/npm install
      args:
        chdir: /app

    # Run npm build on RedHat
    - name: Run npm build on RedHat
      command: /usr/bin/npm run build
      args:
        chdir: /app
      when: ansible_distribution=="RedHat"
      ignore_errors: true

    # Run npm build on Ubuntu
    - name: Run npm build on Ubuntu
      command: /usr/bin/npm run build
      args:
        chdir: /app
      when: ansible_distribution=="Ubuntu"
      ignore_errors: true
      tags:
        - second

    # Install Apache Web Server on Ubuntu machine
    - name: Install Apache Web Server on Ubuntu machine
      apt:
        name: apache2
        state: latest
        update_cache: yes
      when: ansible_distribution=="Ubuntu"

    # Install Apache Web Server on RedHat machine
    - name: Install Apache Web Server on RedHat machine
      yum:
        name: httpd
        state: latest
        update_cache: yes
      when: ansible_distribution=="RedHat"

    # Enable Apache Web Server Service on Ubuntu machine
    - name: Enable Apache Web Server Service on Ubuntu machine
      service:
        name: apache2
        enabled: true
        state: started
      when: ansible_distribution=="Ubuntu"

    # Enable Apache Web Server Service on RedHat machine
    - name: Enable Apache Web Server Service on RedHat machine
      service:
        name: httpd
        enabled: true
        state: started
      when: ansible_distribution=="RedHat"

    # Copy index.html to Default Apache Document root
    - name: Copy index.html to Default Apache Document root
      copy:
        src: /app/build/
        dest: /var/www/html/
        remote_src: yes


    # Configure Apache to use custom index.html on RedHat worker node
    - name: Configure Apache to use custom index.html on RedHat worker node
      ansible.builtin.replace:
         path: /etc/httpd/conf/httpd.conf  # Path to the Apache configuration file on the remote machine
         regexp: "^<LocationMatch \"^/+$\">(.|\n)*<\/LocationMatch>$"
         replace: |
           <Directory /var/www/html>
           Options -Indexes FollowSymLinks
           AllowOverride None
           Require all granted
           </Directory>

           DirectoryIndex index.html

           Alias /poweredby.png /usr/share/httpd/icons/apache_pb3.png
           Alias /system_noindex_logo.png /usr/share/httpd/icons/system_noindex_logo.png
      when: ansible_distribution=="RedHat"
